######################################################################
# Automatically generated by qmake (3.1) Sun Jul 19 20:44:10 2026
######################################################################

CONFIG+=console
QT += core widgets sql network
TEMPLATE = app
TARGET = server
INCLUDEPATH += .

# Input
HEADERS += businesslogic.h \
           databasemanager.h \
           score.h \
           scoredao.h \
           serverwindow.h \
           student.h \
           studentdao.h \
           tcpserver.h \
           ui_serverwindow.h \
           user.h \
           userdao.h
FORMS += serverwindow.ui
SOURCES += businesslogic.cpp \
           databasemanager.cpp \
           main.cpp \
           scoredao.cpp \
           serverwindow.cpp \
           studentdao.cpp \
           tcpserver.cpp \
           userdao.cpp
